### ISSUE TITLE
Add meta-schema to check for $ref entries not under an allOf

### ISSUE THREAD

**Issue by robherring** [devicetree-org/dt-schema#19]
While this seems like a logical way to have a base schema and additional constraints:

```
a-prop:
  $ref: types.yaml#/definitions/a-type
  enum: [1,2,3,4]

```
It doesn't actually work. Google 'json-schema sub classing' for more details. The correct form requires the $ref to be either alone (description can be ignored) or under an 'allOf':

```
a-prop:
  allOf:
    - $ref: types.yaml#/definitions/a-type
  enum: [1,2,3,4]

```
