### ISSUE TITLE
Allow clock-output-names to have a list of descriptions

### ISSUE THREAD

**Issue by mripard** [devicetree-org/dt-schema#33]
clock-output-names will most of the time (always?) be a list of strings that is under control of the device tree itself, so we cannot really mandate a list of values.

Therefore, using something like

```
clock-output-names:
  items:
    - description: First clock to name
    - description: Second clock to name
```
However, the meta-schema seems to reject it
