### ISSUE TITLE
True is not of type 'integer', 'string'

### ISSUE THREAD

**Issue by Demon000** [devicetree-org/dt-schema#90]
Commit 99646e265f78c0f34f8597393d14c668fc59fe62 doesn't take into account the possibility of having an if condition based on the value of a boolean.
Do we want this, or should I work around it (can't really think of how)?

```
    allOf:
      - if:
          properties:
            adi,single-ended:
              const: true
        then:
          properties:
            reg:
              minimum: 1
```
